/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UsersDialog.java
 *
 * Created on Sep 28, 2011, 1:13:00 AM
 */
package sda.client.gui.dialog.user;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import sda.bo.User;
import sda.comunication.encryption.Encryption;
import sda.comunication.especification.Especification;
import sda.manager.rmi.RemoteServiceInterface;

public class UsersDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = 1L;
	User user = null;
    DefaultTableModel modelTable = null;
    JTable tableUsers = null;
    
    /** Creates new form UsersDialog */
    public UsersDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;

        // Move the window
        setLocation(x, y);
        
        updateListUsers();
        setVisible(true);
    }
    
    /**
     * Metodo que seta os dados do banco de dados na tabela
     */
    private void updateListUsers() {
        List<User> listUsers = null;

        //Conexao RMI onde invoca metodo remoto para retornar todos os objetos User
        try {
            Registry reg = LocateRegistry.getRegistry(Especification.MANAGER_ADDR, Especification.RMI_PORT);
            RemoteServiceInterface stub = (RemoteServiceInterface) reg.lookup(Especification.RMI_NAME);
            listUsers = stub.retrieveAllUsers();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

        //Transforma de Lista para Vector de User
        User[] users = new User[0];
        if (listUsers != null) {
                //Descriptografa o objeto
                Encryption encryption = new Encryption();
                users = new User[listUsers.size()];
                for (int i = 0; i < listUsers.size(); i++) {
                        users[i] = encryption.decrypt(listUsers.get(i));
                }
        }
        
        modelTable = new DefaultTableModel();
        tableUsers = new JTable(modelTable);
        tableUsers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableUsers.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (tableUsers.getSelectedRow() >= 0 && (user == null || !user.getUser().equals(modelTable.getValueAt(tableUsers.getSelectedRow(), 1).toString()))) {
                    user = new User();
                    user.setName(modelTable.getValueAt(tableUsers.getSelectedRow(), 0).toString());
                    // só aceita user login em letra minúscula
                    user.setUser(modelTable.getValueAt(tableUsers.getSelectedRow(), 1).toString().toLowerCase());
                }
            }
        });
        jScrollPane1.setViewportView(tableUsers);

        modelTable.addColumn("Nome");
        modelTable.addColumn("Usuário");
		
        //Preenche a tabela com os dados
        for (User user : users) {
            modelTable.addRow(new Object[] {user.getName(), user.getUser(), ""});
        }
        jScrollPane1.updateUI();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuários");
        setResizable(false);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBtnCancel(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBtnRemove(evt);
            }
        });

        jButton3.setText("Cadastrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBtnAdd(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionBtnAdd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionBtnAdd
        dispose();
        new AddUserDialog((java.awt.Frame)getParent(), true, true);
    }//GEN-LAST:event_actionBtnAdd

    private void actionBtnRemove(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionBtnRemove
        if (user != null && !user.getName().trim().equals("")) {
            //Encriptografa o objeto 
            Encryption encryption = new Encryption();
            User personSend = encryption.encrypt(user);

            try {
                Registry reg = LocateRegistry.getRegistry(Especification.MANAGER_ADDR, Especification.RMI_PORT);
                RemoteServiceInterface stub = (RemoteServiceInterface) reg.lookup(Especification.RMI_NAME);
                stub.deleteUser(personSend);
                user = null;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            updateListUsers();
        }
    }//GEN-LAST:event_actionBtnRemove

    private void actionBtnCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionBtnCancel
        dispose();
    }//GEN-LAST:event_actionBtnCancel

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UsersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UsersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UsersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UsersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                UsersDialog dialog = new UsersDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
