/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GuiMain.java
 *
 * Created on Oct 20, 2011, 11:46:22 AM
 */
package sda.repository.server;

import java.awt.Color;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Deivide
 */
public class GuiMain extends javax.swing.JFrame {

    private Thread serverThread;
    private Server server;
    
    /** Creates new form GuiMain */
    public GuiMain() {
        setLookAndFeel();
        initComponents();
    }
    
    /**
     * Método que define o tema de exibição do frame.
     */
    private void setLookAndFeel() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GuiMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(GuiMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(GuiMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(GuiMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnStart = new javax.swing.JMenuItem();
        btnStop = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SDA Servidor");
        setResizable(false);

        txtArea.setColumns(20);
        txtArea.setEditable(false);
        txtArea.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        txtArea.setRows(5);
        txtArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(txtArea);

        jMenu1.setForeground(new java.awt.Color(255, 0, 0));
        jMenu1.setText("Servidor");

        btnStart.setText("Executar");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuStartServer(evt);
            }
        });
        jMenu1.add(btnStart);

        btnStop.setText("Parar");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuStopServer(evt);
            }
        });
        jMenu1.add(btnStop);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionMenuStartServer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuStartServer
        btnStart.setEnabled(false);
        btnStop.setEnabled(true);
        jMenu1.setForeground(Color.GREEN);
        txtArea.setText("Iniciando modulo de Repositorios (REPOSITORY)            [OK]");
        
        File f = new File("download");
		if (!f.exists())
			f.mkdir();
		
        server = new Server();
        server.addEventListener(new Listener() {
        	public void appendTxt(String txt) {
        		txtArea.append(txt);
        	}
        });
        serverThread = new Thread(server);
        serverThread.start();
    }//GEN-LAST:event_actionMenuStartServer

    private void actionMenuStopServer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuStopServer
        btnStart.setEnabled(true);
        btnStop.setEnabled(false);
        txtArea.setText("");
        jMenu1.setForeground(Color.RED);
        server.finish();
        serverThread.interrupt();
    }//GEN-LAST:event_actionMenuStopServer

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GuiMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnStart;
    private javax.swing.JMenuItem btnStop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables

}
